service: serverless-hello-world-aws

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 128
  
functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
